spring:
  servlet:
    multipart:
      max-file-size: 100000KB
      max-request-size: 100000KB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:TEST
    driver-class-name: org.h2.Driver
    username: username
    password: password
    hikari:
      idle-timeout: 10000
  jpa:
    properties:
      hibernate:
        hbm2ddl:
           auto: create
        format_sql: false
    show-sql: false

        
        